apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nousresearch

resources:
  - ../../base

images:
  - name: app-image
    newName: registry.144.91.77.245.sslip.io/dokploy-fleet-nousresearch-nousresearch
    newTag: 171d191b09b6dfb0631b4dfcf6c6e637d0e4ba35
