apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nousresearch

resources:
  - ../../base

images:
  - name: app-image
    newName: registry.144.91.77.245.sslip.io/dokploy-fleet-nousresearch-nousresearch
    newTag: 0d1cb25dd2f9430f28622cf020f4edd7c04f4a8d
