apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nousresearch

resources:
  - ../../base

images:
  - name: app-image
    newName: registry.144.91.77.245.sslip.io/dokploy-fleet-nousresearch-nousresearch
    newTag: 0658020c2a5d9ee330267e48f9663ecea149726f
