---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dokploy-fleet-ghcr
  namespace: nousresearch
spec:
  encryptedData:
    .dockerconfigjson: AgAiBUOL8OlRebWwvQ2WgYYX3cOAy1GEG3HXNHZTI7Uxk1fFMhfE8BB88/T85vsO3x/b8JtCauzz9xe2DMZrIgQxbc9oS7wm/wxoucqzzdt8K7KxJiv47Je5ljWKHLi3rz1kx95mWI7cjj/jBwcbYaRzrjBnSSHmhEzgzSl4voIINKkzRujNrDI6HZel8sFXFQOCh7z+bLlzPYov0Il4XyIQRiiA6JZuUlTMn4dNg8guXGa0xQ75m0gWP+f5ILy6AKlstvm9RFRf8IP7kXnIHgg4hi7RDmp8if34y8KXYCzOPRtyeJS5xoxi+Ms46LuJ9I+dNniDHji92Q1Lbj3e0KaJI98Nw8GSb1RGB5KC1OMqfdDZJxVhIyAYnPiwihWjBo98Nu/1lu74Pdyytn4zMwxNH9kxAwAKU3QWx8uUhk1NrWhYGCI1fEf0mU05Q20HPSkFgD6EVBaIimOvkFQiMUAGy2ohQYNdOqUaov37nuC+wWRfTYO5n7A8eK+R7P+851kIOyAMcYIPOHRs+bFx3nlubQNHkblrndm9FoYJLrScIuT5Xv9ti0DX2H0c2lWOEPA/zxLhbBq6oHxEY+4KFNnWdrKHw4g56Od50SsrNiDkOVqrirMb9GUyd71l16QwH9rtnj2leseAkaZ1zpdzKFMrKuM0AUBHQ4G+pLBh013kAufaIQN91R57BSE9cdTyQl1r41Sxt4MaVT15oZEbSI94SAbMfcwXmNAItpOgfCU8I3sy4ru7oq51wd4QB6EoxDLAt/XnAlxWVkGeqFPQ3IvLNwuGrPeUq7+tjx/pdJgwUx/LUdbLLkwM4UANB6pIcP/knhQ6LL80vZqoXBocM5SfYq55qnAGBVS2a1HOKn/Hk6HvgJ8KyKzpllM5Z5XejmQzCh0m7zyQPSx4uTDim6rH74Arcn09XJSeuBFxbaueRHoCC0mNTEEc
  template:
    metadata:
      name: dokploy-fleet-ghcr
      namespace: nousresearch
    type: kubernetes.io/dockerconfigjson
