apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: nousresearch
spec:
  encryptedData:
    api-token: AgAhG3nYTeHZXwJiKCxcI9hzXXEpE+GZDy4yg24CYnh9+LdyNAwjBtBS/WwJWgYwCXruhUM611I8/j1Hnr3KgEz2jL0xAQDyisr0SpRpYm9R1AyFjIC2xoMbvhnYlNOK8kHdxIrTLmLoq0eiy4fJIqriZDdQE6z70UZ/BBwNP/R8bisapUQSNCZshBq+1CmZf3w1B8qpuCG6FerpjdlJzCrdhVBH945lzbh1rfPPyXhkrEWhtMa/T047AVgTMoLH+9rHO1cvEunIWCcWcSzJBkPH7ZXW7pwiOib5Y66DsThbCK8dLSNZGVKd467f2+sVoYCet20puePiIwU8rN8bb7aRcymFFumdP3ZW+rFDSQYmeMDXq80znagb5PV0Xta+IQ+Q/HZiFF8WphZoaqGPVErWFBvQyP3VnOifvNLY0k6rneakPYeTSmuW4pfaV8HEugmmPQRayMaEtzB4Yz7aNFWX953WoUsCASQDNCiI8ekXkaCyFKG7wE4kNXS5OGTQ5QveiCkFmIdxlSswkzXYFaT6JeKWFyp55a/xd4DeL4Cl8Sx+t4AOczferimOcCV+Lz/240UDdHw0sYOfS4X51o4+kqYV7usAi5BH5erwVewCt8cPMh5l45xQUzFxWvWb70lKr75gJGoxAmV+E9NMOzgnAUNL211Xh8nn6LjPsXmB1fdukajbolBg8d95FzYKd6fnnfbENw42iSk//PfSK/2C01QC+Wp/IqfcI9Xq28STOQgz/ZqILu6N
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: nousresearch
