apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nousresearch
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: nousresearch
    server: https://kubernetes.default.svc
  ignoreDifferences:
    - group: networking.k8s.io
      kind: Ingress
      namespace: nousresearch
      name: nousresearch-live
      managedFieldsManagers:
        - cert-manager-challenges
    - group: networking.k8s.io
      kind: Ingress
      namespace: nousresearch
      name: nousresearch-www-redirect
      managedFieldsManagers:
        - cert-manager-challenges
  source:
    repoURL: https://github.com/gateszhangc/nousresearch.git
    targetRevision: main
    path: deploy/overlays/prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
